name: Bluesky to Discord

on:
  schedule:
    - cron: "*/5 * * * *"  # 매 5분마다 실행
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.0.0'

      - name: Debug npm
        run: npm config set loglevel verbose

      - name: Install dependencies
        run: npm ci

      - name: Run bot
        env:
          BSKY_HANDLE: devilmaycry5.bsky.social
          BSKY_APP_PASSWORD: ${{ secrets.BSKY_APP_PASSWORD }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          set -x
          node index.js
