name: Bluesky to Discord

on:
  schedule:
    - cron: "*/5 * * * *"  # 매 5분마다 실행
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use a compatible Node.js version

      - name: Install dependencies
        run: |
          npm ci --verbose

      - name: Run bot
        env:
          BSKY_HANDLE: devilmaycry5.bsky.social
          BSKY_APP_PASSWORD: ${{ secrets.BSKY_APP_PASSWORD }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          set -x
          node index.js

      - name: Debug npm environment
        run: |
          npm config list
          npm install --dry-run

          
